--DROP TABLE REVISION;
CREATE  TABLE IF NOT EXISTS REVISION (
  REPO VARCHAR NOT NULL,
  PATH VARCHAR NOT NULL,
  CTIME TIMESTAMP NOT NULL,
  YEAR INT,
  WEEK INT,
  ADDED INT,
  REMOVED INT,
  DELTA INT,
  AUTHOR VARCHAR,
  PRIMARY KEY (REPO, PATH, CTIME)
  );
 
CREATE INDEX IF NOT EXISTS YEAR ON REVISION (YEAR);
CREATE INDEX IF NOT EXISTS WEEK ON REVISION (WEEK);
CREATE INDEX IF NOT EXISTS CTIME ON REVISION (CTIME);
CREATE INDEX IF NOT EXISTS REPO ON REVISION (REPO);
CREATE INDEX IF NOT EXISTS AUTHOR ON REVISION (AUTHOR);
